name: AY1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      logging_errors:
        type: boolean
        default: false
        description: 'Turns on/off errors logging'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.11"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run all tests
        run: python -m pytest && echo "All tests past!"
  
  build_and_push_to_dockerhub:

    runs-on: ubuntu-latest

    needs: test
    if: github.event_name == "push"

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: baldazay/weather-app:latest
  
  deploy_to_azure:
    runs-on: ubuntu-latest
    needs: build_and_push_to_dockerhub

    if: github.event_name == "push"

    steps:
      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run docker image
        uses: Azure/webapps-deploy@v2
        with:
          app-name: mars-weather-app
          image: ${{ secrets.DOCKER_USERNAME }}/weather-app:latest


      

